name: 'Label pull requests'
description: 'Label pull request based on comments'
author: 'Verint'
inputs:
  pull_number: 
    required: true
    description: 'pull request number'
  token: 
    required: true
    description: 'github token'  
outputs:
  labels: 
    description: 'The lables that were applied on the pull request'
runs:
  using: 'node16'
  main: 'dist/index.js'
