name: 'Label pull requests'
description: 'Label pull request based on comments'
author: 'Verint'
inputs:
  pull_number: 
    required: true
    description: 'pull request number'
  token: 
    required: true
    description: 'github token'  
outputs:
  commit_types: 
    description: 'The commit types from in the pull request and commit messages'
runs:
  using: 'node16'
  main: 'dist/index.js'
