name: 'Label pull requests'
description: 'Label pull request based on comments'
author: 'Verint'
inputs:
  prNumber: 
    required: true
    description: 'pull request number'
  token: 
    required: true
    description: 'github token'  
outputs:
  log: # id of output
    description: 'Output log. Just for debugging'
runs:
  using: 'node16'
  main: 'dist/index.js'
